[project]
name = "data-science"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.13.7",
    "pre-commit>=4.2.0",
]

[dependency-groups]
dev = []
