[project]
name = "data-science"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.13.0",
    "nbformat>=5.10.4",
    "pandas>=2.2.3",
]
