defaults:
  - data: data
  - _self_
  
n_splits: 5
params:
  num_leaves: 512
  objective: multiclass
  max_depth: -1
  learning_rate: 0.01
  boosting: gbdt
  feature_fraction: 0.9
  bagging_freq: 3
  bagging_fraction: 0.9
  bagging_seed: 11
  random_state: 42
  verbosity: -1
  num_class: 5
